[package]
name = "everydaygui"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.15.0"
futures = "0.3.30"
image = "0.25.1"
wgpu = "0.19"
winit = "0.29"
ttf-parser = "0.20.0"
fontdue = "0.8.0"
