[package]
name = "everydaygui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.15.0"
futures = "0.3.30"
image = "0.25.1"
wgpu = "0.19"
winit = "0.29"
